### ISSUE TITLE
[인프라] 리액트 앱 생성

### ISSUE THREAD

**Issue by pekopekopekopayo** [pulza/front#1]
## 필요사항

- [ ] 리액트 앱 구축
- [ ] 작업자 입맛에 맞게 설정값 셋팅

## 확인사항
- [ ] 페이지 렌더링이 잘 되는지 확인

**Comment by pekopekopekopayo** [comment]
@oct-sky-out 이거 작업을 부탁드립니다.

**Comment by oct-sky-out** [comment]
@pekopekopekopayo 확인해주세요

**Comment by oct-sky-out** [comment]
@pekopekopekopayo 참고로 전역 상태관리 툴(리덕스)은 설정을 따로 안했어요.
앱이 작은만큼 굳이 필요가 없을거같아요.
굳이 필요하다면 ```useContext``` 혹은 ```useReducer```를 사용하는게 차라리 나을거같아요.
